
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vspkfhdtavnroldcthwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcGtmaGR0YXZucm9sZGN0aHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDkxMzYsImV4cCI6MjA1NzI4NTEzNn0.2FvxagksqtmZF1gdiVA1p_WFi0ZwW6QoZ1Axcu77uwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Get the current URL to use as redirect URL
const getRedirectTo = () => {
  if (typeof window === 'undefined') return undefined;
  
  // Use the current host and origin for redirects
  const currentUrl = window.location.origin;
  console.log("Setting redirect URL to:", currentUrl);
  return currentUrl;
};

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    }
  }
);

// Set up auth state change listener
if (typeof window !== 'undefined') {
  // Update authentication configuration for redirects
  supabase.auth.setSession({
    access_token: '',
    refresh_token: ''
  }).then(({ data, error }) => {
    if (error) {
      console.error('Error setting session:', error);
    } else {
      console.log('Session configuration updated');
    }
  });
  
  // Configure the auth state change listener
  supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
      // The redirectTo option is used when signing in or refreshing tokens
      console.log('Auth state changed:', event);
    }
  });
}
